#
# https://gitlab.com/gitlab-org/gitlab/tree/master/lib/gitlab/ci/templates/Nodejs.gitlab-ci.yml
#
image: node:latest

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

stages:
  - testing
  - deployment

jest:
  stage: testing
  script:
    - npm run test:unit:ci

surge:
  stage: deployment
  script:
    - npm install -g @quasar/cli
    - npm install -g surge
    - quasar build
    - surge dist/spa grabovsky.surge.sh

